apiVersion: v1
kind: Service
metadata:
  labels:
    service: ocr-backend
  name: ocr-backend
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: LoadBalancer
  selector:
    service: ocr-backend