# Generated by Django 2.1.15 on 2023-06-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyitemelement',
            old_name='HistoryItem',
            new_name='history_item',
        ),
    ]
