# Generated by Django 2.1.15 on 2023-06-25 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0002_auto_20230625_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 20, 5, 26, 304213)),
            preserve_default=False,
        ),
    ]
