apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: model-server
  name: model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: model-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        service: model-server
    spec:
      containers:
      - image: mostafa1/model-server
        name: model-server
        imagePullPolicy: Always
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1000m"
          limits:
            memory: "6144Mi"
            cpu: "1500m"                    
      restartPolicy: Always