name: Build application

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/UnoApp/global.json

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - run: |
        & dotnet tool update --global uno.check --version 1.12.1
        & uno-check -v --ci --non-interactive --fix
      name: Run Uno Check

    - name: Restore
      run: msbuild -t:restore src/UnoApp/OCRApp.sln

    - name: Build
      run: msbuild -m src/UnoApp/OCRApp.sln

    - name: Publish Android APK
      run: dotnet publish src/UnoApp/OCRApp.Mobile/OCRApp.Mobile.csproj -f:net7.0-android -c:Release -p:RunAOTCompilation=true

    - name: Upload Android APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: src/UnoApp/OCRApp.Mobile/bin/Release/net7.0-android/android-arm64/publish/com.companyname.OCRApp-Signed.apk
